version: "3.8"

services:
  ghostshutter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostshutter
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    restart: unless-stopped
